resource "azurerm_resource_group" "bastion_rg" {
  name     = "${local.project}-bastion-rg"
  location = var.location

  tags = var.tags
}

#
# Secrets with password autogenerated
#
resource "random_password" "bastion_password" {
  length           = 12
  special          = true
  override_special = "!$#%"
}

resource "azurerm_key_vault_secret" "bastion_admin_login_password" {
  name         = "bastion-admin-login-password"
  value        = random_password.bastion_password.result
  key_vault_id = data.azurerm_key_vault.kv.id

  lifecycle {
    ignore_changes = [
      value,
    ]
  }
}

resource "azurerm_subnet" "bastion_subnet" {
  name                 = "bastion-subnet"
  resource_group_name  = data.azurerm_resource_group.rg_vnet.name
  virtual_network_name = data.azurerm_virtual_network.vnet.name
  address_prefixes     = var.cidr_subnet_bastion
}

resource "azurerm_network_interface" "bastion_nic" {
  name                = "bastion-nic"
  location            = var.location
  resource_group_name = azurerm_resource_group.bastion_rg.name

  ip_configuration {
    name                          = "bastion"
    subnet_id                     = azurerm_subnet.bastion_subnet.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = data.azurerm_public_ip.bastion_pip.id
  }

}

resource "azurerm_windows_virtual_machine" "windows_10_pro_spot" {
  name                = "${local.project}-w19-vm"
  resource_group_name = azurerm_resource_group.bastion_rg.name
  location            = var.location
  size                = "Standard_D2as_v4"
  priority            = "Spot"
  eviction_policy     = "Deallocate"
  admin_username      = "devopslab"
  admin_password      = random_password.bastion_password.result
  network_interface_ids = [
    azurerm_network_interface.bastion_nic.id,
  ]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2019-Datacenter"
    version   = "latest"
  }
}
