apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${NAME}
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # Add labels to your application object.
  labels:
    name: ${NAME}
    domain: ${DOMAIN}
spec:
  project: ${ARGOCD_PROJECT_NAME}
  source:
    targetRevision: ${GIT_TARGET_REVISION}
    repoURL: ${GIT_REPO_URL}
    path: ${HELM_PATH}
    helm:
      valuesObject:
        _argocdProjectName: ${ARGOCD_PROJECT_NAME}
        _argocdProjectName1: ${ARGOCD_PROJECT_NAME}
        _azureWorkloadIdentityClientId: ${WORKLOAD_IDENTITY_CLIENT_ID}
        _gitRepoUrl: ${GIT_REPO_URL}
        _gitTargetRevision: ${GIT_TARGET_REVISION}
        _helmPath: ${HELM_PATH}
        ciao: pippo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ${NAMESPACE}
  syncPolicy:
    automated: {}
  revisionHistoryLimit: 10
