name: Manual Dispatch Workflow

on:
  workflow_dispatch:

jobs:
  echo_message:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Echo a message
      run: echo "Hello, this is a message from your self-hosted runner!"
